name: bloc_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  multiple_result:  ^5.1.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.2
  email_validator: '^2.1.16'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  injectable_generator: ^2.1.3

flutter:
  uses-material-design: true